#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.3
#  in conjunction with Tcl version 8.6
#    Jun 29, 2020 11:14:15 AM CEST  platform: Windows NT
#    Jun 29, 2020 12:52:47 PM CEST  platform: Windows NT

import sys
import tkinter as tk


try:
    import ttk

    py3 = False
except ImportError:
    import tkinter.ttk as ttk

    py3 = True

def set_Tk_var():
    global currentplayer
    currentplayer = tk.StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None






